### ISSUE TITLE
Paid account still trying to log on to Telstra

### ISSUE THREAD

**Issue by host1le** [aussieaddons/plugin.video.nrl-live#657] opened 2018-02-11 02:50 UTC
I change logon details from Telstra to Paid however credentials still ask for Telstra ID. In 2018 Live Pass is being linked to NRL account but when I put those details in and try to watch content it tries to log into Telstra and say wrong username password

**Comment by glennguy** [comment] 2018-02-12 12:38
Hi @host1le 
Last year there were three options:
Free Telstra Live Pass
Paid nrl.com Live Pass subscription ( credit card details go directly to nrl.com)
In app purchase (billed through your app store)

I'm having another look into it but at the moment we can't support the in app purchases through google play/app store, there's no easy way to get the purchase token out of your phone in order to use in our add-on.

Unfortunately this year it seems they have removed the paid nrl.com option in favor of the in app subscription. I'll keep trying, just waiting for my free 7 day trial subscription to start working and I can do a bit more investigating.

**Comment by host1le** [comment] 2018-02-12 14:05
Thanks for getting back to me mate I’m very happy you are still looking into it.

Just wondering though if this is something that might be worth investigating:
On my iPhone NRL app I select ‘more’, select the bit for ‘NRL live pass”, where it asks me to sign in, which I do using my free NRL account (can be set up easily online).
It then asks me if I want to purchase using iTunes. Once I did, it links to my NRL account and is tied to that log in. I then tested to see if this work with your app but didn’t expect it to because 1. Your app looks like it only uses Telstra ID to log in, and 2. Its very clear on the website that iTunes live pass wont work on android and android purchase wont work on apple.
I then got on to apple and had them reverse the subscription. Now this got me thinking, I’m assuming that your Kodi app is based on the Android app like this: https://apkplz.com/android-apps/nrl-official-app-apk-download ? If so & the users first jumped on to their own or a mates android phone, got the app and logged in to their NRL account, and bought a live pass though google play store, it should now be linked to their NRL account on the android app. If your kodi app then allowed them to log in with their NRL accounts, wouldn’t their live pass be active on that account?

Just a thought.

Anyway, thanks again for taking the time to try to get this sorted. It would be marvellous if you do, and fingers crossed you’re able to work it out before the season begins

Have a good one mate, all the best.

Luke


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by glennguy** [comment] 2018-02-13 12:01
No worries, happy to be trying to get it sorted.

I'm fearful that the linking to the nrl.com account is only for marketing/analytics/tracking purposes. Hopefully not though! So far the app seems to not be playing very well for me though. I've cancelled my sub and it runs til the 19th, but the app keeps telling me that there's no subscription on my google play account, despite the fact that the traffic to their servers is coming back with a positive response. Reading all the 1 star reviews in the play store I'm getting a better picture of what's going on!

But yes, if the nrl.com account does indeed hold the credentials needed to access the service once linked, then that will be how we will do it. 

The AFL app is quite kind in that once you've confirmed your subscription (at least for the free one) it actually displays your login token on the screen. Let's hope the NRL app does the same if I can actually manage to log in to it!

**Comment by glennguy** [comment] 2018-02-19 00:40
@host1le 
Good news (I think)
Thanks to the last nrl app update on Android you can actually log in now. And it appears that the subscription info is indeed linked to the NRL account. I'll get it happening within the next week :)

**Comment by host1le** [comment] 2018-02-19 01:23
That’s some fantastic news there mate, well done!!!.

So is it like I suggested, the live pass would need to be purchased on an android phone?

Sent from my iPhone

On 19 Feb 2018, at 11:41 am, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


@host1le<https://github.com/host1le>
Good news (I think)
Thanks to the last nrl app update on Android you can actually log in now. And it appears that the subscription info is indeed linked to the NRL account. I'll get it happening within the next week :)

**Comment by glennguy** [comment] 2018-02-19 07:28
I don't think so. Can't be sure 100% but all that has to be done is login to your nrl.com account on your phone and (at least on Android) click restore app store purchase and it should pick it up. Should be the same for iphone. Once the account is linked it doesn't really matter where it comes from.

**Comment by host1le** [comment] 2018-02-19 07:45
See that’s what I would have thought, but when you look at the fine print on this page

https://www.nrl.com/nrl-app-terms-and-conditions/

You can see the following in each of the respective sections

[image1.jpeg]

[image2.jpeg]

Sent from my iPhone

On 19 Feb 2018, at 6:28 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think so. Can't be sure 100% but all that has to be done is login to your nrl.com<http://nrl.com> account on your phone and (at least on Android) click restore app store purchase and it should pick it up. Should be the same for iphone. Once the account is linked it doesn't really matter where it comes from.

**Comment by glennguy** [comment] 2018-02-27 11:39
@host1le I've just seen your reply now, though I can't see the images you've attached. Still working on updating things, I've managed to successfully retrieve a login token from an in app subscription.

**Comment by host1le** [comment] 2018-02-27 11:45
They were just screenshots of the nrl live terms and conditions. The Android section says that a subscription purchased through google play store will not work on apple devices, and they apple section says that a subscription purchased with iTunes account won’t work with android.

As you can only really subscribe on your phone, and both me and my wife have iPhones, I was wondering if I would need to borrow a mates android, log into the nrl app, and purchase a subscription on his device in order for it to work on your app, or if an iTunes purchase would work.

Sent from my iPhone

On 27 Feb 2018, at 10:39 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


@host1le<https://github.com/host1le> I've just seen your reply now, though I can't see the images you've attached. Still working on updating things, I've managed to successfully retrieve a login token from an in app subscription.

**Comment by glennguy** [comment] 2018-02-27 12:57
Ah ok. I think we should be ok. In any case you get a 1 week free trial. As long as the purchase gets linked with an NRL.com account the add-on should be happy

**Comment by host1le** [comment] 2018-02-28 00:35
K. I’ll give it a go tonight

Sent from my iPhone

On 27 Feb 2018, at 11:57 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah ok. I think we should be ok. In any case you get a 1 week free trial. As long as the purchase gets linked with an NRL.com<http://NRL.com> account the add-on should be happy

**Comment by glennguy** [comment] 2018-03-01 12:33
@host1le I've been making some progress. The changes are published in another branch, the zip file is here: https://github.com/aussieaddons/plugin.video.nrl-live/archive/2018_changes.zip

Once you link your subscription to your nrl.com account it should (fingers crossed) work!

Even though you don't need a subscription to view most (if not all) of the videos under the videos category, the addon still requires it for now (makes for easy testing)

Bonus - the videos are available at up to 1080p, and at 50fps!! Let's hope the match replays are the same. They're taking a bit longer to get done as the videos are embedded in a web page, and are hosted on livestream instead of ooyala/telstra. Don't hold your breath for live games though, they're likely to still be bandwidth starved.

Speaking of the live games, I'll do my best to make sure they're up and running as soon as possible. It's impossible to do any work on until they're on the air, so that makes it a bit hard to know what's going to happen.

**Comment by crowdedthehouse** [comment] 2018-03-02 08:24
Hi, how do run this update? I uninstalled the NRL add-on, downloaded the zip file above, uploaded it to my NAS and then searched for it in Kodi and ran it. It is still producing the same error:

"play.py (23) - TelstraAuthException: Please check your username and password in settings"

**Comment by glennguy** [comment] 2018-03-02 08:41
@crowdedthehouse  this means that the error is from having incorrect username or password supplied in the addon's settings. I can see that you have the subscription type set to the free telstra offer. This means that the username/password are your Telstra ID login, whereas the in-app subscription is your nrl.com login. I'll update the settings page before a proper release to make this clearer.  

So if you've got an in app subscription that you're trying to use, change the subscription type to paid. Otherwise if you're a Telstra customer and you haven't linked your mobile service to a Telstra ID, follow this link: http://hub.telstra.com.au/sp2017-nrl-app and get started. 

Let me know if you need anymore help or if you're successful.

**Comment by crowdedthehouse** [comment] 2018-03-02 10:26
Worked it out! My login for NRL.com and Telstra ID are both my email address. The password for both is just the difference of one letter being an upper case for one and a lower case for the other!

All working now!

On a side note, I notice that the Recent/News videos are quite old and the newest ones aren't listed. Are they not being pulled properly?

**Comment by glennguy** [comment] 2018-03-02 11:06
If you're seeing Recent/News then you're not running the version I posted here.

The version number from manually downloading the zip like from the link above is set to 0.0.0 - Kodi will automatically 'update' to the current released version which would seem has happened to you. So uninstall/reinstall the zip, and turn automatic updates off for this addon. Don't forget to turn it back on once I've put a proper release out in the development repository (with a bit of luck this weekend sometime) to make sure you stay up to date.

**Comment by glennguy** [comment] 2018-03-02 12:37
ok @crowdedthehouse @host1le 
Changes are finalised for now and a new build is available from the development repository - disregard the link above now. @crowdedthehouse make sure automatic updates are back on now.

The settings page is now much clearer as to what login info you need.

No idea if live matches will work, we'll have to wait and see. Also still waiting for Telstra to get the full match replays added back in. First it was meant to be January, then February......

Let me know how you go

Thanks

Glenn

**Comment by crowdedthehouse** [comment] 2018-03-02 15:45
i uninstalled the entire repository to be safe, reinstalled and ran updates. My login works, but it's still showing the Recent/News landing page and showing old news videos still. The login page is same as the V1.2.3. I'll go back to 0.0.0 for now to view latest news. Thanks for all the effort!

**Comment by glennguy** [comment] 2018-03-02 21:33
@crowdedthehouse 
Install our development repository, details are here: http://aussieaddons.com/development/

Each time we commit a change to the code a new version will be almost instantly available for update from the development repo. Once we're happy that it's working nicely and nothing is screwed up then a release to the main repository will be made. You can have both repositories installed with no issue.

**Comment by host1le** [comment] 2018-03-06 11:06
Hey mate tried it out tonight. Started out promising until it said my credentials were wrong. I had a look and it had my nrl account name and password in the Telstra areas. I clicked remove stored logins but nothing happened so I clicked defaults and it removed the login details.

Thing is, now I can’t put the right ones in. Only thing I can actual click on is subscription type and remove stored liking token

Sent from my iPhone

On 3 Mar 2018, at 8:33 am, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


@crowdedthehouse<https://github.com/crowdedthehouse>
Install our development repository, details are here: http://aussieaddons.com/development/

Each time we commit a change to the code a new version will be almost instantly available for update from the development repo. Once we're happy that it's working nicely and nothing is screwed up then a release to the main repository will be made. You can have both repositories installed with no issue.

**Comment by glennguy** [comment] 2018-03-06 11:19
@host1le 
The settings will grey out (can't click) the login settings that don't apply to the subscription type, so just pop it over to Paid and it should open up those boxes to click in.

**Comment by host1le** [comment] 2018-03-06 11:21
Tried switch back and forth, both Telstra and NRL is greyed out. Tried uninstall and install but still no luck

Sent from my iPhone

On 6 Mar 2018, at 10:19 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


@host1le<https://github.com/host1le>
The settings will grey out (can't click) the login settings that don't apply to the subscription type, so just pop it over to Paid and it should open up those boxes to click in.

**Comment by glennguy** [comment] 2018-03-06 11:25
What version of Kodi are you running? Also have you restarted Kodi? I've found some weird behaviour after modifying how the settings page runs, usually fixed with a restart.

**Comment by host1le** [comment] 2018-03-06 12:25
Sorry mate, in bed now, I’ll try to check tomorrow

Sent from my iPhone

On 6 Mar 2018, at 10:25 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of Kodi are you running? Also have you restarted Kodi? I've found some weird behaviour after modifying how the settings page runs, usually fixed with a restart.

**Comment by ozziemark** [comment] 2018-03-07 09:22
Hello

I'm also experiencing the greyed issue on the NRL app

I reset my android box about a week ago.
Kodi is version 17.6
NRL is version 1.2.4.

I'm able to get the AFL & Netball working but in the NRL app both the Telstra & the nrl.com remained greyed regardless of the Subscription type selected.

Regards

Mark

**Comment by glennguy** [comment] 2018-03-07 10:55
@ozziemark @host1le
I can see the issue on Android, works fine on windows for some reason. Will test Linux next and I'll get it sorted before tomorrow night's match hopefully.

**Comment by crowdedthehouse** [comment] 2018-03-07 11:42
Just tried to install on Windows, also not working there.

The following link is dead
https://github.com/aussieaddons/plugin.video.nrl-live/archive/2018_changes.zip 

I installed from repo-devel.zip

is that the correct one?

**Comment by host1le** [comment] 2018-03-07 14:28
Hey mate, don’t know if this is pertinent or not but I’m running my Kodi on an Nvidia Shield TV, which I believe is an android device. I’m also getting the weekly subscription to Live pass though Apple ID so will be able to confirm whether it works or not once I’m able to log into app

Luke

Sent from my iPhone

On 7 Mar 2018, at 9:55 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


@ozziemark<https://github.com/ozziemark> @host1le<https://github.com/host1le>
I can see the issue on Android, works fine on windows for some reason. Will test Linux next and I'll get it sorted before tomorrow night's match hopefully.

**Comment by glennguy** [comment] 2018-03-07 22:18
@crowdedthehouse yes, the development repo is the best place to get it from
at the moment. I pushed a fix for the greyed out settings this morning, let
me know if it's working for you.

On 7 Mar. 2018 22:42, "crowdedthehouse" <notifications@github.com> wrote:

Just tried to install on Windows, also not working there.

The following link is dead
https://github.com/aussieaddons/plugin.video.nrl-
live/archive/2018_changes.zip

I installed from repo-devel.zip

is that the correct one?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/aussieaddons/plugin.video.nrl-live/issues/657#issuecomment-371112794>,
or mute the thread

**Comment by ozziemark** [comment] 2018-03-08 06:38
G'day GlennGuy

I grabbed the file you pushed and installed. Version was 0.0.0 and Telstra or nrl.com were enabled depending on the Subscription type selected.

All good.

When I updated it, it installed 1.2.4 and as expected the logon details are greyed out, but the details I input with version 0.0.0 remain, so I'm good to go.

Thanks for you quick work on this.

Regards

Mark

**Comment by glennguy** [comment] 2018-03-08 08:34
Hey @ozziemark 

Thanks for the feedback. We're at version 1.2.4-3-ge277b26 on the [development repo](http://aussieaddons.com/development/) if you wanted to install that. I'm waiting for tonight's match to start streaming so I can get it up and running. Changes will be pushed to the development repo before the main one.

**Comment by host1le** [comment] 2018-03-08 09:24
Hey mate,

Managed to put my details in and log in. Earlier could see tonight’s game as upcoming. Now it should be live but it’s disappeared and I can only see future upcoming games under live section

Sent from my iPhone

On 8 Mar 2018, at 7:34 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @ozziemark<https://github.com/ozziemark>

Thanks for the feedback. We're at version 1.2.4-3-ge277b26 on the development repo<http://aussieaddons.com/development/> if you wanted to install that. I'm waiting for tonight's match to start streaming so I can get it up and running. Changes will be pushed to the development repo before the main one.

**Comment by glennguy** [comment] 2018-03-08 09:25
@ozziemark @host1le @crowdedthehouse 
Version 1.2.5 is up in the main and development repos

If it's not showing in the repo:
(in estuary skin)
go to add-ons
click the open box icon at the top left
install from repository
right click/long press/ 'c' button on our repo and select 'Check For Updates'
should be there now.

Also some more good news: this year the resolution has been effectively bumped up - we're in 1024x576 with no black borders. Still a very low bitrate (1.5Mbps) but much better than the last two years.

Cheers

Glenn

**Comment by glennguy** [comment] 2018-03-08 09:25
@host1le I've just been feverishly working on it for the last 30 minutes, see above :)

**Comment by host1le** [comment] 2018-03-08 09:30
Working! YOU ARE A LEGEND!!!

Sent from my iPhone

On 8 Mar 2018, at 8:25 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


@host1le<https://github.com/host1le> I've just been feverishly working on it for the last 30 minutes, see above :)

**Comment by ozziemark** [comment] 2018-03-08 09:48
G'day GlennGuy

I was able to downloading NRL version 1.2.5 using check for updates.

Telstra or nrl.com are enabled depending on the Subscription type selected.
Live match is working.

Thanks for you efforts.

Regards

Mark

**Comment by glennguy** [comment] 2018-03-08 11:36
@host1le @ozziemark Thanks for the kind words and thanks for helping with testing!

**Comment by crowdedthehouse** [comment] 2018-03-08 13:44
I didn't get around to trying it out tonight as my WiFi is playing sillybuggers. The NRL mobile app was crashing and I still can't log into that. Garbage update of the official app. Should have just stuck to last years working one. I was forced to watch it on myfeed4u with a gazillion popups to navigate through.

Anyways, I just did the update and an log in. Everything seems to be working so hopefully my WiFi doesn't crap itself tomorrow night!

Thanks so much for all your work and let us know if you need anything else tested out.

Do you have a Paypal address? Would love to send $5 your way and shout you a beer! Everyone else should as well!

**Comment by host1le** [comment] 2018-03-09 04:19
Hi mate,

I was just wondering if 720p was the max that the live games could be streamed at. I think I was reading that the AFL app can stream at a higher resolution.

In any case do you have a PayPal account or one of the new pay IDs set up so I can send a little gratitude your way

Luke

Sent from my iPhone

On 8 Mar 2018, at 10:36 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


@host1le<https://github.com/host1le> @ozziemark<https://github.com/ozziemark> Thanks for the kind words and thanks for helping with testing!

**Comment by host1le** [comment] 2018-03-09 04:27
YOU ARE A LEGEND !!!!!!!!

Sent from my iPhone

On 8 Mar 2018, at 8:25 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


@host1le<https://github.com/host1le> I've just been feverishly working on it for the last 30 minutes, see above :)

**Comment by glennguy** [comment] 2018-03-09 06:53
Hey guys, just quickly - update to v1.2.6 to get tonight's games listing properly. Knights vs Sea Eagles is up right now

**Comment by glennguy** [comment] 2018-03-09 07:24
@crowdedthehouse  @host1le 
Thanks again for the words of encouragement.

We've thought about accepting donations but the main concern is that once management for the various content providers see money changing hands over here, whether it's a legit donation/gratitude or otherwise they'll not look upon it favorably. And in that case no one would end up happy. Saying thanks is enough motivation for me, plus you guys are all contributing by helping with testing it out.

Regarding stream resolution, yeah 1024x576  1.5Mb/s is the best we'll get. AFL live matches have the exact same resolution/bitrate.

The other videos for NRL this year though go up to 1080p with a pretty good bitrate. Last nights match extended highlights is 2.7Mb/s.

**Comment by host1le** [comment] 2018-03-09 07:38
Fair enough. Well you do have our eternal gratitude.

With regards to the resolution, as you can see from the pic, my highest for streaming is only 720 (1.6Mb/s)


[image1.jpeg]

Luke

from my iPhone

On 9 Mar 2018, at 6:24 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:

1024x576 1.5Mb/s

**Comment by glennguy** [comment] 2018-03-09 09:09
Looks like things are broken again, will get fix out soon

**Comment by host1le** [comment] 2018-03-09 09:48
Mate there’s no rush as at least we can watch it now, but you are a dead set legend.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by crowdedthehouse** [comment] 2018-03-09 10:57
Watched the Kngihts game perfectly. Thanks again! What a thriller!

But then the Cowboys match didn't work. The error I get is:

play.py (29) - UnboundLocalError: local variable 'token' referenced before assignment

Kodi on Windows 10, Kodi 17.6, NRL app 1.2.6

**Comment by glennguy** [comment] 2018-03-09 23:32
status update: I got the live match working last night. Long story short - Telstra hadn't turned on authorisation as of the first two games (anyone could watch it even without a login) but that seems to be fixed now, so thats why it stopped working. I've got the authorisation working, just still having issues with the free live pass option but I think I know why now as well. 
At the very least I can get it up and running later today (time permitting) with the nrl.com login (which you link to the free live pass in the app anyway)

**Comment by ebertinat** [comment] 2018-03-10 05:31
Gday Mate,
Thought I would let you know that your version 1.2.6 works if the free login is used in the nrl login. I have the free login linked as you mentioned in your last post and so far the first game is streaming live ok! Hope this helps you and thanks for the great app.

**Comment by glennguy** [comment] 2018-03-10 05:46
Hi all,

v1.2.7 is in the repo, it will fix the issue from last night's second match. The process for grabbing the free live pass has changed a lot and it's taking me a bit longer than I thought to get going. The workaround for now is to sign up for a nrl.com account in the app, and link your free live pass to it. Then use the nrl.com settings in the addon.

Cheers

Glenn

**Comment by glennguy** [comment] 2018-03-10 12:46
Ok, Version 1.3.0 is here. Free Telstra live pass is working all good now after a marathon effort, login however you wish! Closing this issue now. Please create a new one if you have any further problems.

Also join our [slack channel](http://slack-invite.aussieaddons.com/) if you're looking for a more real-time response for troubleshooting.

Thanks heaps to everyone for helping to test this.

Cheers

Glenn

**Closed by glennguy** 2018-03-10 12:46 UTC

**Comment by glennguy** [comment] 2018-03-10 12:49
Also @host1le with regards to the streaming resolution in the settings, I hadn't updated that yet but that isn't an accurate representation of what the *actual* stream is, just a guide based on what has been in the past. If you have a keyboard attached to Kodi press 'o' and it'll bring up actual stats for the stream.

Even though the replay streams are encoded at 1080p with a reasonable bitrate, they don't look much better than SD sometimes anyway. Audio is pretty garbage too, sounds equivalent of 64kbps mp3/ 22khz
