### ISSUE TITLE
Won't Play Any Videos

### ISSUE THREAD

**Issue by hooleydooley7** [aussieaddons/plugin.video.nrl-live#51] opened 2017-03-01 11:14 UTC
I click on all the videos and it plays about 12 secs of footage before it freezes.

**Comment by glennguy** [comment] 2017-03-02 06:08
Hi @hooleydooley7

I just need a bit of info from you in order to help further. Can you (after unsuccessfully playing a video) follow the [log upload guide](http://kodi.wiki/view/Log_file/Easy) and report back with the link?

Also can you tell me what replay streaming mode you have set in the add-on's settings? Try toggling to the other one and see if the issue is still there.

Thanks!

**Comment by hooleydooley7** [comment] 2017-03-08 01:49
Hi,
I'm unsure how to upload a log file and yes I have messed around with all the settings with no avail. I did tho manage to watch live nrl but just replays freeze after 13 secs.

Sent from my iPhone

On 2 Mar. 2017, at 4:08 pm, Glenn Guy <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @hooleydooley7<https://github.com/hooleydooley7>

I just need a bit of info from you in order to help further. Can you (after unsuccessfully playing a video) follow the log upload guide<http://kodi.wiki/view/Log_file/Easy> and report back with the link?

Also can you tell me what replay streaming mode you have set in the add-on's settings? Try toggling to the other one and see if the issue is still there.

Thanks!

**Comment by glennguy** [comment] 2017-03-08 07:26
There's a guide in the link that is posted in my last reply, it will walk
you through step by step.

But first, a lot of people that have issues have been resolving them by
upgrading to Kodi v17, so perhaps give that a go before anything.

**Closed** 2018-03-02 12:26 UTC
